// sveltekit-min-todo-app-with-dynamodb-30min-challenge-orthoclase/src/lib/components/TodoItem.svelte
<script lang="ts">
	import { trpcClient } from '$lib/adapter/trpcClient';
	import type { TodoProps } from '$lib/entity/Todo';

	const {
		todo,
		withRefetchListTodo
	}: {
		todo: TodoProps;
		withRefetchListTodo: (promise: Promise<unknown>) => void;
	} = $props();

	function handleOnChangeTitle(event: Event) {
		const target = event.target as HTMLInputElement;
		const title = target.value;
		trpcClient.todo.changeTitle.mutate({
			id: todo.id,
			title
		});
	}

	function handleOnClickToggleCompleted() {
		withRefetchListTodo(trpcClient.todo.toggleStatus.mutate({ id: todo.id }));
	}
</script>

<li
	class={[
		todo.completed ? 'bg-gray-300' : 'bg-amber-300',
		'flex items-center justify-between gap-4 rounded-sm p-4'
	]}
>
	<input class="border-none bg-white/50" value={todo.title} onchange={handleOnChangeTitle} />
	<button onclick={handleOnClickToggleCompleted}>
		{todo.completed ? 'リセット' : '終わった！'}
	</button>
</li>

// nuxt3-min-todo-app/components/TodoItem.vue
<script setup lang="ts">
import type { Todo } from "~/lib/L1.domain/Todo";

defineProps<{
  todo: Todo;
}>();

defineEmits<{
  startTodo: [todoId: string];
  completeTodo: [todoId: string];
  resetTodo: [todoId: string];
  changeTodoTitle: [todoId: string, title: string];
}>();
</script>

<template>
  <li
    :class="[
      todo.status.getValue() === 'InProgress' && 'bg-yellow-100',
      todo.status.getValue() === 'Completed' && 'bg-green-100',
      todo.status.getValue() === 'NotStarted' && 'bg-gray-100',
    ]"
    class="min-w-80 p-4"
  >
    <div class="flex items-center justify-center gap-2">
      <input
        :value="todo.title.getValue()"
        class="rounded border-none bg-white/50 p-2"
        @change="
          $emit('changeTodoTitle', todo.id.getValue(), $event.target.value)
        "
      />
      <span class="rounded bg-gray-500/50 p-2 font-bold">
        <button
          v-if="todo.status.getValue() === 'NotStarted'"
          @click="$emit('startTodo', todo.id.getValue())"
        >
          start
        </button>
        <button
          v-else-if="todo.status.getValue() === 'InProgress'"
          @click="$emit('completeTodo', todo.id.getValue())"
        >
          complete
        </button>
        <button v-else @click="$emit('resetTodo', todo.id.getValue())">
          reset
        </button>
      </span>
    </div>
  </li>
</template>
